# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\working\CMRC-ReportSystem\ReportSystem\UiCode\ShipParameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetShipParameter(object):
    def setupUi(self, SetShipParameter):
        SetShipParameter.setObjectName("SetShipParameter")
        SetShipParameter.resize(655, 408)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SetShipParameter)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(SetShipParameter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(SetShipParameter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_daily_report = QtWidgets.QComboBox(SetShipParameter)
        self.comboBox_daily_report.setObjectName("comboBox_daily_report")
        self.comboBox_daily_report.addItem("")
        self.comboBox_daily_report.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_daily_report)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(SetShipParameter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox_three_days = QtWidgets.QComboBox(SetShipParameter)
        self.comboBox_three_days.setObjectName("comboBox_three_days")
        self.comboBox_three_days.addItem("")
        self.comboBox_three_days.addItem("")
        self.comboBox_three_days.addItem("")
        self.comboBox_three_days.addItem("")
        self.comboBox_three_days.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_three_days)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(SetShipParameter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_five_days = QtWidgets.QComboBox(SetShipParameter)
        self.comboBox_five_days.setObjectName("comboBox_five_days")
        self.comboBox_five_days.addItem("")
        self.comboBox_five_days.addItem("")
        self.comboBox_five_days.addItem("")
        self.comboBox_five_days.addItem("")
        self.comboBox_five_days.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_five_days)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(SetShipParameter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.comboBox_4 = QtWidgets.QComboBox(SetShipParameter)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(SetShipParameter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox_manual = QtWidgets.QComboBox(SetShipParameter)
        self.comboBox_manual.setObjectName("comboBox_manual")
        self.comboBox_manual.addItem("")
        self.comboBox_manual.addItem("")
        self.comboBox_manual.addItem("")
        self.comboBox_manual.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_manual)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.textEdit = QtWidgets.QTextEdit(SetShipParameter)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(SetShipParameter)
        QtCore.QMetaObject.connectSlotsByName(SetShipParameter)

    def retranslateUi(self, SetShipParameter):
        _translate = QtCore.QCoreApplication.translate
        SetShipParameter.setWindowTitle(_translate("SetShipParameter", "船舶设置"))
        self.label.setText(_translate("SetShipParameter", "航次号:"))
        self.label_2.setText(_translate("SetShipParameter", "日报发送间隔（天数）："))
        self.comboBox_daily_report.setItemText(0, _translate("SetShipParameter", "0"))
        self.comboBox_daily_report.setItemText(1, _translate("SetShipParameter", "999"))
        self.label_3.setText(_translate("SetShipParameter", "三天预报发送间隔（天数）："))
        self.comboBox_three_days.setItemText(0, _translate("SetShipParameter", "1"))
        self.comboBox_three_days.setItemText(1, _translate("SetShipParameter", "0"))
        self.comboBox_three_days.setItemText(2, _translate("SetShipParameter", "2"))
        self.comboBox_three_days.setItemText(3, _translate("SetShipParameter", "3"))
        self.comboBox_three_days.setItemText(4, _translate("SetShipParameter", "999"))
        self.label_4.setText(_translate("SetShipParameter", "五天预报发送间隔（天数）："))
        self.comboBox_five_days.setItemText(0, _translate("SetShipParameter", "999"))
        self.comboBox_five_days.setItemText(1, _translate("SetShipParameter", "1"))
        self.comboBox_five_days.setItemText(2, _translate("SetShipParameter", "0"))
        self.comboBox_five_days.setItemText(3, _translate("SetShipParameter", "2"))
        self.comboBox_five_days.setItemText(4, _translate("SetShipParameter", "3"))
        self.label_5.setText(_translate("SetShipParameter", "合同库中船舶状态（不可修改）："))
        self.comboBox_4.setItemText(0, _translate("SetShipParameter", "1"))
        self.comboBox_4.setItemText(1, _translate("SetShipParameter", "0"))
        self.comboBox_4.setItemText(2, _translate("SetShipParameter", "2"))
        self.label_6.setText(_translate("SetShipParameter", "人工修改船舶状态："))
        self.comboBox_manual.setItemText(0, _translate("SetShipParameter", "999"))
        self.comboBox_manual.setItemText(1, _translate("SetShipParameter", "0"))
        self.comboBox_manual.setItemText(2, _translate("SetShipParameter", "1"))
        self.comboBox_manual.setItemText(3, _translate("SetShipParameter", "2"))
        self.textEdit.setHtml(_translate("SetShipParameter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">999：不发送</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">0：每天发送</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">1：每隔一天发送</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">2：每隔两天发送</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ff0000;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; color:#ff0000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">0：服务中在航</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">1：服务中在港</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">2：待服务</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">999：未设置</span></p></body></html>"))
